Class Cartes :
    def __init__(self,name,points,couleur,jouee):
        self.name = name
        self.points = points
        self.couleur = couleur
        self.jouee = jouee

'''liste cartes, un seul jeu ici'''
'1c' = Cartes('As',1,'coeur',False)
'2c' = Cartes('2',2,'coeur',False)
'3c' = Cartes('3',3,'coeur',False)
'4c' = Cartes('4',4,'coeur',False)
'5c' = Cartes('5',5,'coeur',False)
'6c' = Cartes('6',6,'coeur',False)
'7c' = Cartes('7',7,'coeur',False)
'8c' = Cartes('8',8,'coeur',False)
'9c' = Cartes('9',9,'coeur',False)
'10c' = Cartes('10',10,'coeur',False)
'Vc' = Cartes('Valet',10,'coeur',False)
'Dc' = Cartes('Dame',10,'coeur',False)
'Rc' = Cartes('Roi',10,'coeur',False)
'1p' = Cartes('As',1,'pique',False)
'2p' = Cartes('2',2,'pique',False)
'3p' = Cartes('3',3,'pique',False)
'4p' = Cartes('4',4,'pique',False)
'5p' = Cartes('5',5,'pique',False)
'6p' = Cartes('6',6,'pique',False)
'7p' = Cartes('7',7,'pique',False)
'8p' = Cartes('8',8,'pique',False)
'9p' = Cartes('9',9,'pique',False)
'11p' = Cartes('10',10,'pique',False)
'Vp' = Cartes('Valet',10,'pique',False)
'Dp' = Cartes('Dame',10,'pique',False)
'Rp' = Cartes('Roi',10,'pique',False)
'1ca' = Cartes('As,False'
'1ca' = Cartes('2',2,'carreau',False)
'1ca' = Cartes('3',3,'carreau',False)
'1ca' = Cartes('4',4,'carreau',False)
'1ca' = Cartes('5',5,'carreau')
'1ca' = Cartes('6',6,'carreau')
'1ca' = Cartes('7',7,'carreau')
'1ca' = Cartes('8',8,'carreau')
'1ca' = Cartes('9',9,'carreau')
'1ca' = Cartes('10',10,'carreau')
'1ca' = Cartes('Valet',10,'carreau')
'1ca' = Cartes('Dame',10,'carreau')
'1ca' = Cartes('Roi',10,'carreau')
